anken/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('users/list/', views.list_user, name='list_user'),
    path('staff/list/', views.list_staff, name='list_staff'),
]

buhin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
#    path('', include('anken.urls')),
    path('admin/', admin.site.urls),
    path('anken/', include('anken.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

]

anken/models.py
from django.db import models
import datetime as dt
from django.utils import timezone
from django.contrib.auth.models import User

inq_type_choice = (("Inq","見積"),
        ("Ord","注文"))
prog_choice = (
        ("InqNow","見積中"),
        ("InqDone","見積完了"),
        ("PartDone","一部完了"),
        ("AllDone","全部完了"),
        )

ope_name = []
n = 0
for i in User.objects.all():
    ope_name.append((str(n),str(i)))
    n += 1

class Anken(models.Model):
    id = models.IntegerField('No.',primary_key=True)
    anken_id = models.CharField('案件番号',max_length=20,default='0001')
    item_name = models.CharField('件名',max_length=20)
    ope_name = models.CharField('担当者',max_length=20)
    created_at = models.DateTimeField('作成日時',default=dt.datetime.now())
    updated_at = models.DateTimeField('更新日時',default=dt.datetime.now())
    inq_type = models.CharField("種類",max_length=10,choices=inq_type_choice,default="Inq")
    progress = models.CharField("進捗",max_length=10,choices=prog_choice,default="InqNow")
    body_num = models.CharField("車台番号",max_length=10,default="0000")

    def __str__(self):
        return self.item_name

anken/views.py
from django.shortcuts import render
from .models import Anken

def index(request):
    param = {"message": "兵庫部品"}
    return render(request, 'anken/index.html', param)

def list_staff(request):
    data = Anken.objects.all()
    params = {'message': '案件一覧（スタッフ用）', 'data': data}
    return render(request, 'anken/staff/list.html', params)

def list_user(request):
    data = Anken.objects.all()
    params = {'message': '案件一覧', 'data': data}
    return render(request, 'anken/users/list.html', params)

anken/templates/anken/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>home</title>
</head>

<body>
	<h1>{{ message }}</h1>
    <a href="/admin">管理画面</a>
    <a href="/anken/list">リスト</a>
</body>

</html>

anken/templates/anken/list.html
<!DOCTYPE html>
<html>
 
<head>
    <meta charset="utf-8" />
    <title>案件一覧</title>
</head>
 
<body>
    <h1>{{ message }}</h1>
    <table border="1">
        <tr>
            <th>No.</th>
            <th>案件番号</th>
            <th>件名</th>
            <th>種類</th>
            <th>進捗</th>
            <th>車台番号</th>
            <th>作成日時</th>
            <th>更新日時</th>
            <th>担当者</th>
        </tr>
        {% for anken in data %}
        <tr>
            <td>{{ anken.id }}</td>
            <td>{{ anken.anken_id }}</td>
            <td>{{ anken.item_name }}</td>
            <td>{{ anken.get_inq_type_display }}</td>
            <td>{{ anken.get_progress_display }}</td>
            <td>{{ anken.body_num }}</td>
            <td>{{ anken.created_at }}</td>
            <td>{{ anken.updated_at }}</td>
            <td>{{ anken.ope_name }}</td>		
        </tr>
        {% endfor %}
    </table>
    <br>
    <hr>
    <a href="{% url "index"  %}">home</a<
</body>
 
</html>

anken/templates/anken/staff/list.html
<!DOCTYPE html>
<html>
 
<head>
    <meta charset="utf-8" />
    <title>案件一覧</title>
</head>
 
<body>
    <h1>{{ message }}</h1>
    <table border="1">
        <tr>
            <th>No.</th>
            <th>案件番号</th>
            <th>件名</th>
            <th>種類</th>
            <th>進捗</th>
            <th>車台番号</th>
            <th>作成日時</th>
            <th>更新日時</th>
            <th>担当者</th>
        </tr>
        {% for anken in data %}
        <tr>
            <td>{{ anken.id }}</td>
            <td>{{ anken.anken_id }}</td>
            <td>{{ anken.item_name }}</td>
            <td>{{ anken.get_inq_type_display }}</td>
            <td>{{ anken.get_progress_display }}</td>
            <td>{{ anken.body_num }}</td>
            <td>{{ anken.created_at }}</td>
            <td>{{ anken.updated_at }}</td>
            <td>{{ anken.ope_name }}</td>		
        </tr>
        {% endfor %}
    </table>
    <br>
    <hr>
    <a href="{% url "home"  %}">home</a<
</body>
 
</html>

anken/templates/anken/users/list.html
<!DOCTYPE html>
<html>
 
<head>
    <meta charset="utf-8" />
    <title>案件一覧</title>
</head>
 
<body>
    <h1>{{ message }}</h1>
    <table border="1">
        <tr>
            <th>No.</th>
            <th>案件番号</th>
            <th>件名</th>
            <th>種類</th>
            <th>進捗</th>
            <th>車台番号</th>
            <th>作成日時</th>
            <th>更新日時</th>
            <th>担当者</th>
        </tr>
        {% for anken in data %}
        <tr>
            <td>{{ anken.id }}</td>
            <td>{{ anken.anken_id }}</td>
            <td>{{ anken.item_name }}</td>
            <td>{{ anken.get_inq_type_display }}</td>
            <td>{{ anken.get_progress_display }}</td>
            <td>{{ anken.body_num }}</td>
            <td>{{ anken.created_at }}</td>
            <td>{{ anken.updated_at }}</td>
            <td>{{ anken.ope_name }}</td>		
        </tr>
        {% endfor %}
    </table>
    <br>
    <hr>
    <a href="{% url "home"  %}">home</a<
</body>
 
</html>

anken/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

anken/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <h1>兵庫部品</h1>
  user: {{ user.username }}
  <hr>
  {{ message }}
  {% if user.is_superuser %}
    <a href="/anken/staff/list">スタッフ用リスト</a>
  {% elif not user.is_superuser %}
    <a href="/anken/users/list">リスト</a>
  {% endif %}
  <hr>
  <p><a href="{% url 'logout' %}">ログアウト</a></p>
{% else %}
  <p>You are not logged in</p>
  <hr>
  <a href="{% url 'login' %}">ログイン</a>
{% endif %}
{% endblock %}